/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 18146a959c6cc316a45758a10af378d2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		AI: Ai;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		GENERATE_PACK: Workflow<Parameters<import("./src/server").GeneratePackWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
